# Generated by Django 5.0.14 on 2026-09-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialdeacceso',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados_app.empleado'),
        ),
        migrations.AlterField(
            model_name='registrodeasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados_app.empleado'),
        ),
    ]
