# Generated by Django 5.0.14 on 2026-09-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('totalGenerado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalPorcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Registro Mensual',
                'verbose_name_plural': 'Registros Mensuales ',
            },
        ),
        migrations.CreateModel(
            name='Aguinaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('montoAguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registroMensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aguinaldos', to='liquidaciones_app.registromensual')),
            ],
            options={
                'verbose_name': 'Aguinaldo',
                'verbose_name_plural': 'Aguinaldos',
            },
        ),
    ]
