# Generated by Django 5.0.14 on 2026-09-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados_app', '0001_initial'),
        ('liquidaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('montoServicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentajeEmpleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_realizados', to='empleados_app.empleado')),
                ('registroMensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_realizados', to='liquidaciones_app.registromensual')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_realizados', to='servicios_app.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Realizado',
                'verbose_name_plural': 'Servicios Realizados',
            },
        ),
    ]
